name: Nestjs Docker Image CI To ECR

on:
  push:
    branches: [ main. actions ]
  pull_request:
    branches: [ main, actions ]

jobs:
  nestjs-to-ecr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Build the Docker image
        run: docker build -t include-nestjs-image ./docker/include-nestjs
      - name: AWS ECR Login
        run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com
      - name: AWS ECR tag settings
        run: docker tag include-nestjs-image public.ecr.aws/${{secrets.AWS_ECR_REGISTRY_ALIAS}}/include-nestjs-image
      - name: AWS ECR public repository Upload docker image
        run: docker push public.ecr.aws/${{secrets.AWS_ECR_REGISTRY_ALIAS}}/include-nestjs-image